print("           x")
print("          xxx ")
print("         XXXXX")
print("        XXXXXXX")
print("       XXXXXXXXX")
print("      XXXXXXXXXXX")
print("     XXXXXXXXXXXXX")
print( "    XXXXXXXXXXXXXXX")
print("           XX")
print("           Xx")
print("          XXXX")
